from django.conf.urls import *
from django.conf.urls.static import static
from django.conf import  settings
from django.contrib import admin
from exam import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import staticfiles
from mysite import session
from mysite.views import logining, index, SAhome, create, update, datamanage, backup, reloading, updateing, resetpwd, personalmodify, personalmodify2,newpersonalmodify, rename
from exam.views import exam_manager, question_manager, addquestion, addquestion_e, updatequestion, listingquestion, review, addexam, alterexam, cancleexam, delete_exam, list_post, new_post, edit_post, delete_post, userinfo, check_topic, member_show, addexam_simulation, alterexam_simulation, addexam_computer, delete_talk , delete_grammar, delete_noun, delete_short_conversation, delete_reading,review_delete_talk,review_delete_grammar,review_delete_noun,review_delete_short_conversation,review_delete_reading, checkduplicate_talk, checkduplicate_short_conversation, checkduplicate_noun, checkduplicate_grammar,checkduplicate_reading, view_score, check, comp, clas, check_s, comp_s, clas_s, subjects, member_select, test, score,next , Continue,contest , listeningpractice, talkpractice ,talkanswer ,ctalkpractice ,short_conversationpractice ,short_conversationanswer ,cshort_conversationpractice, writepractice, grammarpractice ,grammaranswer ,cgrammarpractice, nounpractice , nounanswer, cnounpractice, readingpractice, readinganswer, creadingpractice, realtest ,yettest, notest,score2


def i18n_javascript(request):
    return admin.site.i18n_javascript(request)


urlpatterns = [
	url(r'^admin/jsi18n', i18n_javascript),
    url(r'^admin/', include(admin.site.urls)),
	url(r'^$', session.session, name='login2'),
	url(r'^index/$', index, name='Index'),
	url(r'^rename/$', rename, name='rename'),
	url(r'^SAhome/$', SAhome, name='SAhome'),
	url(r'^SAhome/create/$', create, name='create'),
	url(r'^SAhome/update/$', update, name='update'),
	url(r'^SAhome/update/updateing/(?P<id>[0-9]+)/$', updateing, name='updateing'),
	url(r'^SAhome/update/resetpwd/(?P<id>[0-9]+)/$', resetpwd, name='ressetpwd'),
	url(r'^SAhome/datamanage/$', datamanage, name='datamanage'),
	url(r'^SAhome/datamanage/backup/$', backup, name='backup'),
	url(r'^SAhome/datamanage/reloading$', reloading, name='reloading'),
	url(r'^exam_manager/$', exam_manager, name='exam_manager'),
	url(r'^question_manager/$', question_manager, name='question_manager'),
	url(r'^addquestion/$', addquestion, name='addquestion'),
	url(r'^addquestion_e/$', addquestion_e, name='addquestion_e'),
	url(r'^updatequestion/$', updatequestion, name='updatequestion'),
	url(r'^listingquestion/$', listingquestion, name='listingquestion'),
	url(r'^review/$', review, name='review'),
	url(r'^addexam/$', addexam, name='addexam'),
	url(r'^alterexam/$', alterexam, name='alterexam'),
	url(r'^alterexam//(?P<qs>.*)/edit/$', views.edit_exam, name='edit_exam'),
	url(r'^cancleexam/$', cancleexam, name='cancleexam'),
	url(r'cancleexam/(?P<pk>[0-9]+)/delete/$', delete_exam.as_view(), name='delete_exam'),
	url(r'^list_post/$', list_post, name='list_post'),
	url(r'^new_post/$', new_post, name='new_post'),
	url(r'^list_post//(?P<qs>.*)/edit/$', edit_post, name='edit_post'),
	url(r'list_post/(?P<pk>[0-9]+)/delete/$', delete_post.as_view(), name='delete_post'),
	url(r'^userinfo/$', userinfo, name='userinfo'),
	url(r'^check_topic/$', check_topic, name='check_topic'),
	url(r'^check_member/$', member_show, name='check_member'),
	url(r'^addexam_simulation/$', addexam_simulation, name='addexam_simulation'),
	url(r'^alterexam_simulation/$', alterexam_simulation, name='alterexam_simulation'),
	url(r'^addexam_computer/$', addexam_computer, name='addexam_computer'),
	url(r'^admin/jsi18n', i18n_javascript),
	url(r'^addquestion_talk/$', views.addquestion_talk, name='addquestion_talk'),
	url(r'^listing_talk/(?P<qs>.*)/edit/$', views.edit_talk, name='edit_talk'),
	url(r'listing_talk/(?P<pk>[0-9]+)/delete/$', delete_talk.as_view(), name='delete_talk'),
	url(r'^results_talk/$', views.search_talk, name='search_talk'),
	url(r'^listing_talk/$', views.listing_talk, name='listing_talk'),
	url(r'^addquestion_short_conversation/$', views.addquestion_short_conversation, name='addquestion_short_conversation'),
	url(r'^listing_short_conversation/(?P<qs>.*)/edit/$', views.edit_short_conversation,
		name='edit_short_conversation'),
	url(r'listing_short_conversation/(?P<pk>[0-9]+)/delete/$', delete_short_conversation.as_view(),
		name='delete_short_conversation'),
	url(r'^results_short_conversation/$', views.search_short_conversation, name='search_short_conversation'),
	url(r'^listing_short_conversation/$', views.listing_short_conversation, name='listing_short_conversation'),
	url(r'^addquestion_noun/$', views.addquestion_noun, name='addquestion_noun'),
	url(r'^listing_noun/(?P<qs>.*)/edit/$', views.edit_noun, name='edit_noun'),
	url(r'listing_noun/(?P<pk>[0-9]+)/delete/$', delete_noun.as_view(), name='delete_noun'),
	url(r'^results_noun/$', views.search_noun, name='search_noun'),
	url(r'^listing_noun/$', views.listing_noun, name='listing_noun'),
	url(r'^addquestion_reading/$', views.addquestion_reading, name='addquestion_reading'),
	url(r'^listing_reading/(?P<qs>.*)/edit/$', views.edit_reading, name='edit_reading'),
	url(r'listing_reading/(?P<pk>[0-9]+)/delete/$', delete_reading.as_view(), name='delete_reading'),
	url(r'^results_reading/$', views.search_reading, name='search_reading'),
	url(r'^listing_reading/$', views.listing_reading, name='listing_reading'),
	url(r'^addquestion_grammar/$', views.addquestion_grammar, name='addquestion_grammar'),
	url(r'^listing_grammar/(?P<qs>.*)/edit/$', views.edit_grammar, name='edit_grammar'),
	url(r'listing_grammar/(?P<pk>[0-9]+)/delete/$', delete_grammar.as_view(), name='delete_grammar'),
	url(r'^results_grammar/$', views.search_grammar, name='search_grammar'),
	url(r'^listing_grammar/$', views.listing_grammar, name='listing_grammar'),
	url(r'^review_listing_reading/$', views.review_listing_reading, name='review_listing_reading'),
    url(r'^review_listing_reading/(?P<qs>.*)/edit/$', views.review_reading, name='review_reading'),
    url(r'review_listing_reading/(?P<pk>[0-9]+)/delete/$',review_delete_reading.as_view(), name='review_delete_reading'),
    url(r'^review_listing_talk/$', views.review_listing_talk, name='review_listing_talk'),
    url(r'^review_listing_talk/(?P<qs>.*)/edit/$', views.review_talk, name='review_talk'),
    url(r'review_listing_talk/(?P<pk>[0-9]+)/delete/$',review_delete_talk.as_view(), name='review_delete_talk'),
    url(r'^review_listing_grammar/$', views.review_listing_grammar, name='review_listing_grammar'),
    url(r'^review_listing_grammar/(?P<qs>.*)/edit/$', views.review_grammar, name='review_grammar'),
    url(r'review_listing_grammar/(?P<pk>[0-9]+)/delete/$',review_delete_grammar.as_view(), name='review_delete_grammar'),
    url(r'^review_listing_noun/$', views.review_listing_noun, name='review_listing_noun'),
    url(r'^review_listing_noun/(?P<qs>.*)/edit/$', views.review_noun, name='review_noun'),
    url(r'review_listing_noun/(?P<pk>[0-9]+)/delete/$',review_delete_noun.as_view(), name='review_delete_noun'),
    url(r'^review_listing_short_conversation/$', views.review_listing_short_conversation, name='review_listing_short_conversation'),
    url(r'^review_listing_short_conversation/(?P<qs>.*)/edit/$', views.review_short_conversation, name='review_short_conversation'),
    url(r'review_listing_short_conversation/(?P<pk>[0-9]+)/delete/$',review_delete_short_conversation.as_view(), name='review_delete_short_conversation'),
	url(r'^addquestion_talk_e/$', views.addquestion_talk2, name='addquestion_talk_e'),
	url(r'^listing_talk_e/$', views.listing_talk2, name='listing_talk_e'),
	url(r'^addquestion_short_conversation_e/$', views.addquestion_short_conversation2, name='addquestion_short_conversation_e'),
	url(r'^listing_short_conversation_e/$', views.listing_short_conversation2, name='listing_short_conversation_e'),
	url(r'^addquestion_noun_e/$', views.addquestion_noun2, name='addquestion_noun_e'),
	url(r'^listing_noun_e/$', views.listing_noun2, name='listing_noun_e'),
	url(r'^addquestion_reading_e/$', views.addquestion_reading2, name='addquestion_reading_e'),
 	url(r'^listing_reading_e/$', views.listing_reading2, name='listing_reading_e'),
	url(r'^addquestion_grammar_e/$', views.addquestion_grammar2, name='addquestion_grammar_e'),
	url(r'^listing_grammar_e/$', views.listing_grammar2, name='listing_grammar_e'),
	url(r'^listing_talk_check/$',views.checkduplicate_talk,name='check_talk'),
	url(r'^listing_short_conversation_check/$',views.checkduplicate_short_conversation,name='check_short_conversation'),
	url(r'^listing_noun_check/$',views.checkduplicate_noun,name='check_noun'),
	url(r'^listing_reading_check/$',views.checkduplicate_reading,name='check_reading'),
	url(r'^listing_grammar_check/$',views.checkduplicate_grammar,name='check_grammar'),
	url(r'^view_score/', view_score, name='view_score'),
	url(r'^check_s/', check_s, name='check_s'),
	url(r'^comp_s/', comp_s, name='comp_s'),
	url(r'^clas_s/', clas_s, name='clas_s'),
	url(r'^check/', check, name='check'),
	url(r'^comp/', comp, name='comp'),
	url(r'^clas/', clas, name='clas'),
	url(r'^subjects/', subjects, name='subjects'),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^member_select/$', member_select, name='member_select'),
	url(r'^results_member/$', views.search_member, name='search_member'),
	url(r'^get_member/$', views.get_member, name='get_member'),
	# url(r'export_excel/$', export_excel, name='export_excel'),
	url(r'^test/$', test, name='test'),
	url(r'^contest/$', contest, name='contest'),
	url(r'^score/$', score, name='score'),
	url(r'^score2/$', score2, name='score2'),
	url(r'^next/$', next, name='next'),
	url(r'^Continue/$', Continue, name='Continue'),
	url(r'^listeningpractice/$', listeningpractice, name='listeningpractice'),
	url(r'^talkpractice/$', talkpractice, name='talkpractice'),
	url(r'^talkanswer/$', talkanswer, name='talkanswer'),
	url(r'^ctalkpractice/$', ctalkpractice, name='ctalkpractice'),
	url(r'^short_conversationpractice/$', short_conversationpractice, name='short_conversationpractice'),
	url(r'^short_conversationanswer/$', short_conversationanswer, name='short_conversationanswer'),
	url(r'^writepractice/$', writepractice, name='writepractice'),
	url(r'^cshort_conversationpractice/$', cshort_conversationpractice, name='cshort_conversationpractice'),
	url(r'^grammarpractice/$', grammarpractice, name='grammarpractice'),
	url(r'^grammaranswer/$', grammaranswer, name='grammaranswer'),
	url(r'^cgrammarpractice/$', cgrammarpractice, name='cgrammarpractice'),
	url(r'^nounpractice/$', nounpractice, name='nounpractice'),
	url(r'^nounanswer/$', nounanswer, name='nounanswer'),
	url(r'^cnounpractice/$', cnounpractice, name='cnounpractice'),
	url(r'^readingpractice/$', readingpractice, name='readingpractice'),
	url(r'^readinganswer/$', readinganswer, name='readinganswer'),
	url(r'^creadingpractice/$', creadingpractice, name='creadingpractice'),
	url(r'^realtest/$', realtest, name='realtest'),
	url(r'^notest/$', notest, name='notest'),
	url(r'^yettest/$', yettest, name='yettest'),
	url(r'^personalmodify/$', personalmodify, name='personalmodify'),
	url(r'^personalmodify2/$', personalmodify2, name='personalmodify2'),
	url(r'^newpersonalmodify/$', newpersonalmodify, name='newpersonalmodify'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
